version: 2

workflows:
  version: 2
  build-test-lint:
    jobs:
      # - ios
      # - android
      # - mac-main-tests
      # - debian-cli-tests

jobs:
  ios:
    working_directory: ~/live-common
    macos:
      xcode: "11.3.0"
    steps:
      - run:
          name: pre-start simulator
          command: xcrun instruments -w "iPhone X (12.4)" || true
      - checkout
      - run:
          name: "versions"
          command: |
            node -v
            yarn -v
            ruby -v
      - run:
          name: Install all
          command: |
            yarn install
            cd mobile-test-app
            bundle install
            yarn
            cd ios && bundle exec pod install
      - run:
          name: run tests
          command: cd mobile-test-app && yarn ios:test
          no_output_timeout: 1h

  android:
    working_directory: ~/live-common
    docker:
      - image: circleci/android:api-28-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout

      - run:
          name: Show list of system-images
          command: sdkmanager --list --verbose | grep system-images

      - run:
          name: Setup emulator
          command: |
            sdkmanager "system-images;android-25;google_apis;armeabi-v7a"
            echo "no" | avdmanager create avd -n test -k "system-images;android-25;google_apis;armeabi-v7a"

      - run:
          name: Launch emulator
          command: |
            export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib
            emulator -avd test -noaudio -no-boot-anim -no-window
          background: true

      - run:
          name: "versions"
          command: |
            node -v
            yarn -v
            ruby -v

      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}-{{ checksum "mobile-test-app/Gemfile.lock" }}
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
            cd mobile-test-app
            bundle install
            yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}-{{ checksum "mobile-test-app/Gemfile.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: run tests
          command: cd mobile-test-app && yarn android:build

  mac-main-tests:
    working_directory: ~/live-common
    macos:
      xcode: "10.2.1"
    steps:
      - checkout
      - run:
          name: "versions"
          command: |
            node -v
            yarn -v
      - run:
          name: Install Dependencies
          command: |
            yarn global add yalc codecov
            yarn install --frozen-lockfile
            cd cli
            yarn --frozen-lockfile
            cd -
            yarn ci-setup-cli
      - run: yarn ci-lint
      - run:
          command: yarn ci-test-common && npx codecov
          no_output_timeout: 1h

  debian-cli-tests:
    working_directory: ~/live-common
    docker:
      - image: circleci/node:12-stretch
    steps:
      # - run: sudo apt-get update
      - run: sudo apt-get install -y libudev-dev libusb-1.0-0-dev jq
      # - run:
      #     name: Install latest yarn
      #     command: |
      #       curl -sS http://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - ;
      #       echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list ;
      #       sudo apt-get update && sudo apt-get install yarn
      #       sudo rm /usr/local/bin/yarn # remove docker yarn
      - checkout
      - run:
          name: "versions"
          command: |
            node -v
            yarn -v
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}-with-cli-{{ checksum "cli/yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            yarn global add yalc codecov
            yarn install --frozen-lockfile
            cd cli
            yarn --frozen-lockfile
            cd -
            yarn ci-setup-cli
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}-with-cli-{{ checksum "cli/yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn ci-lint
