version: 2

workflows:
  version: 2
  build-test-lint:
    jobs:
      - mac
      - debian

jobs:
  mac:
    working_directory: ~/live-common
    macos:
      xcode: "10.2.1"
    steps:
      - run: brew unlink node && brew install node@8 jq && brew link --overwrite node@8 --force
      - checkout
      - run: node -v
      - run: yarn install
      - run: yarn global add yalc
      - run: yarn ci-test-cli

  debian:
    working_directory: ~/live-common
    docker:
      - image: circleci/node:8-stretch-browsers
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y libudev-dev libusb-1.0-0-dev jq
      - run:
          name: Install latest yarn
          command: |
            curl -sS http://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - ;
            echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list ;
            sudo apt-get update && sudo apt-get install yarn
            sudo rm /usr/local/bin/yarn # remove docker yarn
      - checkout
      - restore_cache:
          keys:
            - v12-yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v12-yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn global add yalc
      - run: yarn ci-lint
      - run: yarn ci-test-common
      - run: yarn ci-test-cli
