name: Tests
on: [pull_request]

jobs:
  macos-main-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: Versions
        run: |
          node -v
          yarn -v
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: |
          yarn global add yalc codecov
          yarn --frozen-lockfile
          cd cli
          yarn --frozen-lockfile
          cd -
          yarn ci-setup-cli
      - name: Deps versions
        run: |
          yarn flow --version
          yar jest --version
      - name: Lint
        run: yarn ci-lint
      - name: Run tests
        run: yarn ci-test-common && npx codecov
        timeout-minutes: 60
  debian-cli-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: Install linux deps
        run: sudo apt-get install -y libudev-dev libusb-1.0-0-dev jq
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: |
          yarn global add yalc codecov
          yarn install --frozen-lockfile
          cd cli
          yarn --frozen-lockfile
          cd -
          yarn ci-setup-cli
      - name: Run CLI tests
        run: yarn ci-test-cli
        timeout-minutes: 60
